---
- name: Setup windows
  hosts: all
  gather_facts: true
  become: yes
  vars:
    windows_login_autologin_enable: true
    windows_rdp_enable: true
  roles:
    - windows_powershell
    - windows_login
    - windows_rdp
    - windows_theme
    - windows_taskbar
    - windows_tools
    - windows_virtualisation
    - windows_services
    # - windows_enhancements
