---

- name: Configure gaming services
  hosts: all
  gather_facts: true
  become: yes
  roles:
    - role: nvidia_drivers
      when: ansible_user != 'vagrant'
    - automation
    - game_launchers
    - game_modding
