---

- name: Handle winRM
  become: true
  failed_when: false
  ansible.windows.win_service:
    name:
      - WinRM
    start_mode: "{{ ansible_user == 'vagrant' | ternary('auto', 'manual') }}"

- name: Handle OpenSSH
  become: true
  failed_when: false
  ansible.windows.win_service:
    name:
      - sshd
    start_mode: "{{ ansible_user == 'vagrant' | ternary('auto', 'manual') }}"

- name: Services to automatic
  become: yes
  failed_when: false
  ansible.windows.win_service:
    name: "{{ item }}"
    start_mode: auto
  loop: "{{ windows_services_automatic }}"

- name: Services to manual
  become: yes
  failed_when: false
  ansible.windows.win_service:
    name: "{{ item }}"
    start_mode: manual
  loop: "{{ windows_services_manual }}"

- name: Services to Delay
  become: yes
  failed_when: false
  ansible.windows.win_service:
    name: "{{ item }}"
    start_mode: delayed
  loop: "{{ windows_services_delayed }}"

- name: Services to Disable
  become: yes
  failed_when: false
  ansible.windows.win_service:
    name: "{{ item }}"
    start_mode: disabled
  loop: "{{ windows_services_disabled }}"
