---

- name: Set Auto login
  become: yes
  ansible.windows.win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon"
    name: "{{ item.name }}"
    data: "{{ item.value }}"
    type: string
    state: "{{ 'present' if windows_login_autologin_enable else 'absent' }}"
  with_items:
    - name: AutoAdminLogon
      value: "{{ 1 if windows_login_autologin_enable else 0 }}"
    - name: DefaultUsername
      value: "{{ windows_login_autologin_user }}"
    - name: DefaultPassword
      value: "{{ windows_login_autologin_password }}"

- name: Ensure personalisation key exists
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
    state: present

- name: Disable lock screen
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
    name: NoLockScreen
    type: dword
    data: "{{ 1 if windows_login_lockscreen_disable else 0 }}"
    state: present

- name: Disable locking the computer
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DisableLockWorkstation
    type: dword
    data: "{{ 1 if windows_login_lockworkstation_disable else 0 }}"
    state: present

- name: Disable the timeout policy
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: InactivityTimeoutSecs
    type: dword
    data: ""
    state: present
