---
- name: Set Auto login
  become: yes
  ansible.windows.win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon"
    name: "{{ item.name }}"
    data: "{{ item.value }}"
    type: string
    state: "{{ windows_login_autologin_enable | ternary('present', 'absent') }}"
  loop:
    - name: AutoAdminLogon
      value: "{{ windows_login_autologin_enable | ternary('1', '0') }}"
    - name: DefaultUsername
      value: "{{ windows_login_autologin_user }}"
    - name: DefaultPassword
      value: "{{ windows_login_autologin_password }}"

- name: Ensure personalisation key exists
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
    state: present

- name: Disable lock screen
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
    name: NoLockScreen
    type: dword
    data: "{{ windows_login_lockscreen_disable | ternary('1', '0') }}"
    state: present

- name: Disable locking the computer
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DisableLockWorkstation
    type: dword
    data: "{{ windows_login_lockworkstation_disable | ternary('1', '0') }}"
    state: present

- name: Disable the timeout policy
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: InactivityTimeoutSecs
    type: dword
    data: "{{ windows_login_lock_timeout }}"
    state: present
